#!/usr/bin/env bash
# Install the harness's conda + pip environment (the harness itself: install-harness.sh). Shared by
# deploy/full/Dockerfile and deploy/full/vbt-harness.def, so the Docker and the Apptainer image run the same steps.
#
#   install-env.sh env     --prefix /opt/conda/envs/vbt --spec-dir deploy/full [--unlocked]
#       conda packages from conda-linux-64.lock (explicit URLs + md5), then pip packages from requirements.lock
#       (exact versions, --no-deps: the lock lists every pip-installed distribution). --unlocked resolves
#       environment.yml + requirements.in instead (what `deploy.sh lock` does to regenerate the locks);
#       --pip-unlocked keeps the conda lock and resolves only requirements.in.
#   install-env.sh export  --prefix /opt/conda/envs/vbt --out DIR
#       write DIR/conda-linux-64.lock and DIR/requirements.lock from an installed environment.
#
# Needs micromamba on PATH (or MAMBA_EXE). Network access goes through the standard HTTPS_PROXY variable; a
# TLS-intercepting proxy's CA is given with SSL_CERT_FILE (the Dockerfile sets it from the optional build secret
# `extra_ca`).
set -euo pipefail

cmd="${1:-}"
[ $# -gt 0 ] && shift
PREFIX=/opt/conda/envs/vbt
SPEC_DIR=""
OUT=""
LOCKED=1
PIP_LOCKED=1
while [ $# -gt 0 ]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2 ;;
    --spec-dir) SPEC_DIR="$2"; shift 2 ;;
    --out) OUT="$2"; shift 2 ;;
    --unlocked) LOCKED=0; PIP_LOCKED=0; shift ;;
    --pip-unlocked) PIP_LOCKED=0; shift ;;
    *) echo "install-env.sh: unknown option $1" >&2; exit 2 ;;
  esac
done
MAMBA="${MAMBA_EXE:-micromamba}"
PY="$PREFIX/bin/python"

# `name==version` of every Python distribution conda installed (pip constraints).
CONDA_DISTS='
from importlib import metadata
for d in metadata.distributions():
    if (d.read_text("INSTALLER") or "").strip() == "conda":
        name = d.metadata["Name"]
        print(f"{name}=={d.version}")
'
# Fail when a pip distribution owns a file a conda package installed (pip replaced that package: conda-meta still
# lists the file). Compares files, so conda names that differ from the distribution (pytorch/torch) count too.
NO_SHADOW='
import json, pathlib, sys, sysconfig
from importlib import metadata
prefix = pathlib.Path(sys.prefix)
site = pathlib.Path(sysconfig.get_paths()["purelib"]).relative_to(prefix)
owner = {}
for p in (prefix / "conda-meta").glob("*.json"):
    rec = json.loads(p.read_text())
    for f in rec.get("files") or []:
        owner[f] = rec["name"]
bad = set()
pip = 0
for d in metadata.distributions():
    if (d.read_text("INSTALLER") or "").strip() != "pip":
        continue
    pip += 1
    for f in d.files or []:
        rel = str(site / f)
        if ".dist-info/" in rel or "__pycache__" in rel:
            continue
        if rel in owner:
            name = d.metadata["Name"]
            bad.add(f"{name}=={d.version} over conda {owner[rel]}")
            break
if bad:
    sys.exit("pip replaced conda packages: " + "; ".join(sorted(bad)))
print(f"{pip} pip distributions on top of {len(set(owner.values()))} conda packages; none replaces a conda package")
'

case "$cmd" in
  env)
    [ -n "$SPEC_DIR" ] || { echo "install-env.sh env: --spec-dir is required" >&2; exit 2; }
    if [ "$LOCKED" = 1 ]; then
      grep -q '^@EXPLICIT' "$SPEC_DIR/conda-linux-64.lock" 2>/dev/null || \
        { echo "install-env.sh: $SPEC_DIR/conda-linux-64.lock is missing or not an explicit lock; run deploy/full/deploy.sh lock" >&2; exit 1; }
      "$MAMBA" create -y -p "$PREFIX" -f "$SPEC_DIR/conda-linux-64.lock"
    else
      "$MAMBA" create -y -p "$PREFIX" -f "$SPEC_DIR/environment.yml"
    fi
    # pip never replaces a conda package: the conda versions are constraints of the resolve, and the check after
    # the install fails the build when a pip distribution shadows one (a pip numpy 2 over conda's numpy 1.26 would
    # break every compiled conda package)
    "$PY" -c "$CONDA_DISTS" > /tmp/vbt-conda-constraints.txt
    if [ "$PIP_LOCKED" = 1 ]; then
      grep -q '==' "$SPEC_DIR/requirements.lock" 2>/dev/null || \
        { echo "install-env.sh: $SPEC_DIR/requirements.lock is missing or empty; run deploy/full/deploy.sh lock" >&2; exit 1; }
      "$PY" -m pip install --no-deps --no-input -r "$SPEC_DIR/requirements.lock"
    else
      "$PY" -m pip install --no-input -c /tmp/vbt-conda-constraints.txt -r "$SPEC_DIR/requirements.in"
    fi
    "$PY" -c "$NO_SHADOW"
    rm -f /tmp/vbt-conda-constraints.txt
    "$MAMBA" clean --all --force-pkgs-dirs --yes >/dev/null
    "$PY" -m pip cache purge >/dev/null 2>&1 || true
    ;;
  export)
    [ -n "$OUT" ] || { echo "install-env.sh export: --out is required" >&2; exit 2; }
    mkdir -p "$OUT"
    { echo "# Explicit conda lock of deploy/full/environment.yml (linux-64). Generated by deploy/full/deploy.sh lock;"
      echo "# do not edit by hand."
      "$MAMBA" env export -p "$PREFIX" --explicit; } > "$OUT/conda-linux-64.lock"
    "$PY" - "$OUT/requirements.lock" <<'EOF'
import sys
from importlib import metadata

rows = []
for dist in metadata.distributions():
    installer = (dist.read_text("INSTALLER") or "").strip()
    if installer != "pip" or dist.read_text("direct_url.json"):   # conda-linked or editable/local: not locked
        continue
    rows.append(f"{dist.metadata['Name']}=={dist.version}")
with open(sys.argv[1], "w") as f:
    f.write("# pip packages of the harness image (exact versions; installed with --no-deps on top of\n"
            "# conda-linux-64.lock). Generated by deploy/full/deploy.sh lock from requirements.in; do not edit by hand.\n")
    f.write("\n".join(sorted(rows, key=str.lower)) + "\n")
print(f"{len(rows)} pip packages locked")
EOF
    ;;
  *)
    echo "usage: install-env.sh env|export [options] (see the header of this file)" >&2
    exit 2
    ;;
esac
